[package]
name = "prism-snp-measure"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "snp-measure"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
